# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '496c2741afeb2293022336b3e0298103' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 496c2741afeb2293022336b3e0298103
  pod 'Alamofire'

end
